
import 'dart:convert';

CountryModelModel countryModelModel = CountryModelModel();
class CountryModelModel{
  String country = "country";
  String currencySign = "currencySign";
  String currencyCode = "currencyCode";
  String dialingCode = "dialingCode";
  String countryCode = "countryCode";
}

Map<String, dynamic> countryInformation = {
  "AF": {
    "country": "Afghanistan",
    "currency": "Afghanistani Afghani",
    "currencyCode": "AFNAFN",
    "currencySign": "؋",
    "dialingCode": "+93",
    "countryCode": "AFG",
  },
  "AM": {
    "country": "Armenia",
    "currency": "Armenian Dram",
    "currencyCode": "AMD",
    "currencySign": "դր",
    "dialingCode": "+374",
    "countryCode": "ARM",
  },
  "AZ": {
    "country": "Azerbaijan",
    "currency": "Azerbaijani Manat",
    "currencyCode": "AZN",
    "currencySign": "₼",
    "dialingCode": "+994	",
    "countryCode": "AZE",
  },
  "BH": {
    "country": "Bahrain",
    "currency": "Bahraini Dinar",
    "currencyCode": "BHD",
    "currencySign": ".د.ب",
    "dialingCode": "+973",
    "countryCode": "BHR",
  },
  "BD": {
    "country": "Bangladesh",
    "currency": "Bangladeshi Taka",
    "currencyCode": "BDT",
    "currencySign": "৳",
    "dialingCode": "+880",
    "countryCode": "BGD",
  },
  "BT": {
    "country": "Bhutan",
    "currency": "Bhutanese Ngultrum",
    "currencyCode": "BTN",
    "currencySign": "Nu.",
    "dialingCode": "+975",
    "countryCode": "BTN",
  },
  "BN": {
    "country": "Brunei",
    "currency": "Brunei Dollar",
    "currencyCode": "BND",
    "currencySign": "\$",
    "dialingCode": "+673",
    "countryCode": "BRN",
  },
  "KH": {
    "country": "Cambodia",
    "currency": "Cambodian Riel",
    "currencyCode": "KHR",
    "currencySign": "៛",
    "dialingCode": "+855",
    "countryCode": "KHM",
  },
  "CN": {
    "country": "China",
    "currency": "Chinese Yuan Renminbi",
    "currencyCode": "CNY",
    "currencySign": "¥",
    "dialingCode": "+86",
    "countryCode": "CHN",
  },
  "CY": {
    "country": "Cyprus",
    "currency": "Cypriot Pound",
    "currencyCode": "CYP",
    "currencySign": "£",
    "dialingCode": "+357",
    "countryCode": "CYP",
  },
  "GE": {
    "country": "Georgia",
    "currency": "Georgian Lari",
    "currencyCode": "GEL",
    "currencySign": "ლ",
    "dialingCode": "+995",
    "countryCode": "GEO",
  },
  "IN": {
    "country": "India",
    "currency": "Indian Rupee",
    "currencyCode": "INR",
    "currencySign": "₹",
    "dialingCode": "+91",
    "countryCode": "IND",
  },
  "ID": {
    "country": "Indonesia",
    "currency": "Indonesian Rupiah",
    "currencyCode": "IDR",
    "currencySign": "Rp",
    "dialingCode": "+62",
    "countryCode": "IDN",
  },
  "IR": {
    "country": "Iran",
    "currency": "Iranian Rial",
    "currencyCode": "IRR",
    "currencySign": "﷼",
    "dialingCode": "+98",
    "countryCode": "IRN",
  },
  "IQ": {
    "country": "Iraq",
    "currency": "Iraqi Dinar",
    "currencyCode": "IQD",
    "currencySign": "ع.د",
    "dialingCode": "+964",
    "countryCode": "IRQ",
  },
  "IL": {
    "country": "Israel",
    "currency": "Israeli New Sheqel",
    "currencyCode": "ILS",
    "currencySign": "₪",
    "dialingCode": "+972",
    "countryCode": "ISR",
  },
  "JP": {
    "country": "Japan",
    "currency": "Japanese Yen",
    "currencyCode": "JPY",
    "currencySign": "¥",
    "dialingCode": "+81",
    "countryCode": "JPN",
  },
  "JO": {
    "country": "Jordan",
    "currency": "Jordanian Dinar",
    "currencyCode": "JOD",
    "currencySign": "د.ا",
    "dialingCode": "+962",
    "countryCode": "JOR",
  },
  "KZ": {
    "country": "Kazakhstan",
    "currency": "Kazakhstani Tenge",
    "currencyCode": "KZT",
    "currencySign": "лв",
    "dialingCode": "+7",
    "countryCode": "KAZ",
  },
  "KW": {
    "country": "Kuwait",
    "currency": "Kuwaiti Dinar",
    "currencyCode": "KWD",
    "currencySign": "د.ك",
    "dialingCode": "+965",
    "countryCode": "KWT",
  },
  "KG": {
    "country": "Kyrgyzstan",
    "currency": "Kyrgyzstani Som",
    "currencyCode": "KGS",
    "currencySign": "лв",
    "dialingCode": "+996",
    "countryCode": "KGZ",
  },
  "LA": {
    "country": "Laos",
    "currency": "Lao Kip",
    "currencyCode": "LAK",
    "currencySign": "₭",
    "dialingCode": "+856",
    "countryCode": "LAO",
  },
  "LB": {
    "country": "Lebanon",
    "currency": "Lebanese Pound",
    "currencyCode": "LBP",
    "currencySign": "£",
    "dialingCode": "+961",
    "countryCode": "LBN",
  },
  "MY": {
    "country": "Malaysia",
    "currency": "Malaysian Ringgit",
    "currencyCode": "MYR",
    "currencySign": "RM",
    "dialingCode": "+60",
    "countryCode": "MYS",
  },
  "MV": {
    "country": "Maldives",
    "currency": "Maldives Rufiyaa",
    "currencyCode": "MVR",
    "currencySign": "Rf",
    "dialingCode": "+960",
    "countryCode": "MDV",
  },
  "MN": {
    "country": "Mongolia",
    "currency": "Mongolian Tugrik",
    "currencyCode": "MNT",
    "currencySign": "₮",
    "dialingCode": "+976",
    "countryCode": "MNG",
  },
  "MM": {
    "country": "	Myanmar (Burma)",
    "currency": "	Myanmar Kyat",
    "currencyCode": "MMK",
    "currencySign": "K",
    "dialingCode": "+95",
    "countryCode": "MMR",
  },
  "NP": {
    "country": "Nepal",
    "currency": "Nepalese Rupee",
    "currencyCode": "NPR",
    "currencySign": "₨",
    "dialingCode": "+977",
    "countryCode": "NPL",
  },
  "KP": {
    "country": "	North Korea",
    "currency": "North Korean Won",
    "currencyCode": "KPW",
    "currencySign": "₩",
    "dialingCode": "+850",
    "countryCode": "PRK",
  },
  "OM": {
    "country": "Oman",
    "currency": "Omani Rial",
    "currencyCode": "OMR",
    "currencySign": "﷼",
    "dialingCode": "+968",
    "countryCode": "OMN",
  },
  "PK": {
    "country": "Pakistan",
    "currency": "Pakistan Rupee",
    "currencyCode": "PKR",
    "currencySign": "₨",
    "dialingCode": "+92",
    "countryCode": "PAK",
  },
  "PS": {
    "country": "Palestine",
    "currency": "Jordanian Dinar",
    "currencyCode": "JOD",
    "currencySign": "د.ا",
    "dialingCode": "+970",
    "countryCode": "PSE",
  },
  "PH": {
    "country": "Philippines",
    "currency": "Philippine Peso",
    "currencyCode": "PHP",
    "currencySign": "₱",
    "dialingCode": "+63",
    "countryCode": "PHL",
  },
  "QA": {
    "country": "Qatar",
    "currency": "Qatari Riyal",
    "currencyCode": "QAR",
    "currencySign": "﷼",
    "dialingCode": "+974",
    "countryCode": "QAT",
  },
  "RU": {
    "country": "Russia",
    "currency": "Russian Ruble",
    "currencyCode": "RUB",
    "currencySign": "₽",
    "dialingCode": "+7",
    "countryCode": "RUS",
  },
  "SA": {
    "country": "Saudi Arabia",
    "currency": "Saudi Arabian Riyal",
    "currencyCode": "SAR",
    "currencySign": "﷼",
    "dialingCode": "+966",
    "countryCode": "SAU",
  },
  "SG": {
    "country": "Singapore",
    "currency": "Singapore Dollar",
    "currencyCode": "SGD",
    "currencySign": "\$",
    "dialingCode": "+65",
    "countryCode": "SGP",
  },
  "KR": {
    "country": "South Korea",
    "currency": "Korean Won",
    "currencyCode": "KRW",
    "currencySign": "₩",
    "dialingCode": "+82",
    "countryCode": "KOR",
  },
  "LK": {
    "country": "Sri Lankan Rupee",
    "currency": "LKR",
    "currencyCode": "LKR",
    "currencySign": "₨",
    "dialingCode": "+94",
    "countryCode": "LKA",
  },
  "SY": {
    "country": "Syria",
    "currency": "Syrian Pound",
    "currencyCode": "SYP",
    "currencySign": "£",
    "dialingCode": "+963",
    "countryCode": "SYR",
  },
  "TW": {
    "country": "Taiwan",
    "currency": "New Taiwan Dollar",
    "currencyCode": "TWD",
    "currencySign": "NT\$",
    "dialingCode": "+886",
    "countryCode": "TWN",
  },
  "TJ": {
    "country": "Tajikistan",
    "currency": "Tajikistan Somoni",
    "currencyCode": "TJS",
    "currencySign": "ЅM",
    "dialingCode": "+992",
    "countryCode": "TJK",
  },
  "TH": {
    "country": "Thailand",
    "currency": "Thai Baht",
    "currencyCode": "THB",
    "currencySign": "฿",
    "dialingCode": "+66",
    "countryCode": "THA",
  },
  "TL": {
    "country": "Timor",
    "currency": "United States Dollar",
    "currencyCode": "USD",
    "currencySign": "\$",
    "dialingCode": "+670",
    "countryCode": "TLS",
  },
  "TR": {
    "country": "Turkey",
    "currency": "Turkish New Lira",
    "currencyCode": "TRY",
    "currencySign": "₺",
    "dialingCode": "+90",
    "countryCode": "TUR",
  },
  "TM": {
    "country": "Turkmenistan",
    "currency": "Turkmenistani Manat",
    "currencyCode": "TMM",
    "currencySign": "T",
    "dialingCode": "+993",
    "countryCode": "TKM",
  },
  "AE": {
    "country": "United",
    "currency": "United Arab Emirates Dirham	",
    "currencyCode": "AED",
    "currencySign": "د.إ",
    "dialingCode": "+971",
    "countryCode": "ARE",
  },
  "UZ": {
    "country": "Uzbekistan",
    "currency": "Uzbekistani Som",
    "currencyCode": "UZS",
    "currencySign": "лв",
    "dialingCode": "+998",
    "countryCode": "UZB",
  },
  "VN": {
    "country": "Vietnam",
    "currency": "Viet Nam Dong",
    "currencyCode": "VND",
    "currencySign": "₫",
    "dialingCode": "+84",
    "countryCode": "VNM",
  },
  "YE": {
    "country": "Yemen",
    "currency": "Yemeni Rial",
    "currencyCode": "YER",
    "currencySign": "﷼",
    "dialingCode": "+967",
    "countryCode": "YEM",
  },
  "DZ": {
    "country": "Algeria",
    "currency": "Algerian Dinar",
    "currencyCode": "DZD",
    "currencySign": "دج",
    "dialingCode": "+213",
    "countryCode": "DZA",
  },
  "AO": {
    "country": "Angola",
    "currency": "Angolan Kwanza",
    "currencyCode": "AOA",
    "currencySign": "Kz",
    "dialingCode": "+244",
    "countryCode": "AGO",
  },
  "BJ": {
    "country": "Benin",
    "currency": "West African CFA",
    "currencyCode": "XOF",
    "currencySign": "CFA",
    "dialingCode": "+229",
    "countryCode": "BEN",
  },
  "BW": {
    "country": "Botswana",
    "currency": "Botswana Pula",
    "currencyCode": "BWP",
    "currencySign": "P",
    "dialingCode": "+267",
    "countryCode": "BWA",
  },
  "BF": {
    "country": "Burkina",
    "currency": "West African CFA",
    "currencyCode": "XOF",
    "currencySign": "CFA",
    "dialingCode": "+226",
    "countryCode": "BFA",
  },
  "BI": {
    "country": "Burundi",
    "currency": "Burundian Franc",
    "currencyCode": "BIF",
    "currencySign": "FBu",
    "dialingCode": "+257",
    "countryCode": "BDI",
  },
  "CV": {
    "country": "Cape Verde",
    "currency": "Cape Verde Escudo",
    "currencyCode": "CVE",
    "currencySign": "\$",
    "dialingCode": "+238",
    "countryCode": "CPV",
  },
  "CM": {
    "country": "Cameroon",
    "currency": "Central African CFA",
    "currencyCode": "XAF",
    "currencySign": "FCFA",
    "dialingCode": "+237",
    "countryCode": "CMR",
  },
  "CF": {
    "country": "Central African Republic (CAR)",
    "currency": "Central African CFA",
    "currencyCode": "XAF",
    "currencySign": "FCFA",
    "dialingCode": "+236",
    "countryCode": "CAF",
  },
  "TD": {
    "country": "Chad",
    "currency": "Central African CFA",
    "currencyCode": "XAF",
    "currencySign": "FCFA",
    "dialingCode": "+235",
    "countryCode": "TCD",
  },
  "KM": {
    "country": "Comoros",
    "currency": "Comorian Franc",
    "currencyCode": "KMF",
    "currencySign": "CF",
    "dialingCode": "+269",
    "countryCode": "COM",
  },
  "CD": {
    "country": "Democratic Republic of the Congo",
    "currency": "Congolese franc",
    "currencyCode": "CDF",
    "currencySign": "FC",
    "dialingCode": "+243",
    "countryCode": "COD",
  },
  "CG": {
    "country": "Republic of the Congo",
    "currency": "Central African CFA",
    "currencyCode": "XAF",
    "currencySign": "FCFA",
    "dialingCode": "+243",
    "countryCode": "COD",
  },
  "DJ": {
    "country": "Djibouti",
    "currency": "Djiboutian Franc",
    "currencyCode": "DJF",
    "currencySign": "Fdj",
    "dialingCode": "+253",
    "countryCode": "DJI",
  },
  "EG": {
    "country": "Egypt",
    "currency": "Egyptian Pound",
    "currencyCode": "EGP",
    "currencySign": "£",
    "dialingCode": "+20",
    "countryCode": "EGY",
  },
  "GQ": {
    "country": "Equatorial",
    "currency": "Central African CFA",
    "currencyCode": "XAF",
    "currencySign": "FCFA",
    "dialingCode": "+240",
    "countryCode": "GNQ",
  },
  "ER": {
    "country": "Eritrea",
    "currency": "Eritrean Nakfa",
    "currencyCode": "ERN",
    "currencySign": "ናቕፋ",
    "dialingCode": "+291",
    "countryCode": "ERI",
  },
  "ET": {
    "country": "Ethiopia",
    "currency": "Ethiopian Birr",
    "currencyCode": "ETB",
    "currencySign": "ብር",
    "dialingCode": "+251",
    "countryCode": "ETH",
  },
  "GA": {
    "country": "Gabon",
    "currency": "Central African CFA",
    "currencyCode": "XAF",
    "currencySign": "FCFA",
    "dialingCode": "+241",
    "countryCode": "GAB",
  },
  "GM": {
    "country": "Gambia",
    "currency": "Gambian Dalasi",
    "currencyCode": "GMD",
    "currencySign": "D",
    "dialingCode": "+220",
    "countryCode": "GMB",
  },
  "GH": {
    "country": "Ghana",
    "currency": "Ghanaian Cedi",
    "currencyCode": "GHS",
    "currencySign": "GH₵",
    "dialingCode": "+233",
    "countryCode": "GHA",
  },
  "GN": {
    "country": "Guinea",
    "currency": "Guinean Franc",
    "currencyCode": "GNF",
    "currencySign": "FG",
    "dialingCode": "+675",
    "countryCode": "PNG",
  },
  "GW": {
    "country": "Guinea-Bissau",
    "currency": "West African CFA",
    "currencyCode": "XOF",
    "currencySign": "CFA",
    "dialingCode": "+245",
    "countryCode": "GNB",
  },
  "KE": {
    "country": "Kenya",
    "currency": "Kenyan Shilling",
    "currencyCode": "KES",
    "currencySign": "KSh",
    "dialingCode": "+254",
    "countryCode": "KEN",
  },
  "LS": {
    "country": "Lesotho",
    "currency": "Lesotho Loti",
    "currencyCode": "LSL",
    "currencySign": "L",
    "dialingCode": "+266",
    "countryCode": "LSO",
  },
  "LR": {
    "country": "Liberia",
    "currency": "Liberian Dollar",
    "currencyCode": "LRD",
    "currencySign": "\$",
    "dialingCode": "+231",
    "countryCode": "LBR",
  },
  "LY": {
    "country": "Libya",
    "currency": "Libyan Dinar",
    "currencyCode": "LYD",
    "currencySign": "ل.د",
    "dialingCode": "+218",
    "countryCode": "LBY",
  },
  "MG": {
    "country": "Madagascar",
    "currency": "Malagasy Ariary",
    "currencyCode": "MGA",
    "currencySign": "Ar",
    "dialingCode": "+261",
    "countryCode": "MDG",
  },
  "MW": {
    "country": "Malawi",
    "currency": "Malawian Kwacha",
    "currencyCode": "MWK",
    "currencySign": "MK",
    "dialingCode": "+265",
    "countryCode": "MWI",
  },
  "ML": {
    "country": "Mali",
    "currency": "West African CFA",
    "currencyCode": "XOF",
    "currencySign": "CFA",
    "dialingCode": "+223",
    "countryCode": "MLI",
  },
  "MR": {
    "country": "Mauritania",
    "currency": "Mauritanian Ouguiya",
    "currencyCode": "MRO",
    "currencySign": "UM",
    "dialingCode": "+222",
    "countryCode": "MRT",
  },
  "MU": {
    "country": "Mauritius",
    "currency": "Mauritian Rupee",
    "currencyCode": "MUR",
    "currencySign": "₨",
    "dialingCode": "+230",
    "countryCode": "MUS",
  },
  "MA": {
    "country": "Morocco",
    "currency": "Moroccan Dirham",
    "currencyCode": "MAD",
    "currencySign": "DH",
    "dialingCode": "+212",
    "countryCode": "MAR",
  },
  "MZ": {
    "country": "Mozambique",
    "currency": "Mozambican Metical",
    "currencyCode": "MZN",
    "currencySign": "MT",
    "dialingCode": "+258",
    "countryCode": "MOZ",
  },
  "NA": {
    "country": "Namibia",
    "currency": "Namibian Dollar",
    "currencyCode": "NAD",
    "currencySign": "\$",
    "dialingCode": "+264",
    "countryCode": "NAM",
  },
  "NE": {
    "country": "Niger",
    "currency": "West African CFA",
    "currencyCode": "XOF",
    "currencySign": "CFA",
    "dialingCode": "+227",
    "countryCode": "NER",
  },
  "NG": {
    "country": "Nigeria",
    "currency": "Nigerian Naira",
    "currencyCode": "NGN",
    "currencySign": "₦",
    "dialingCode": "+234",
    "countryCode": "NGA",
  },
  "RW": {
    "country": "Rwanda",
    "currency": "Rwandan Franc",
    "currencyCode": "RWF",
    "currencySign": "FRw",
    "dialingCode": "+250",
    "countryCode": "RWA",
  },
  "ST": {
    "country": "Sao Tome and Principe",
    "currency": "Sao Tome Dobra",
    "currencyCode": "STD",
    "currencySign": "Db",
    "dialingCode": "+239",
    "countryCode": "	STP",
  },
  "SN": {
    "country": "Senegal",
    "currency": "West African CFA",
    "currencyCode": "XOF",
    "currencySign": "CFA",
    "dialingCode": "+221",
    "countryCode": "SEN",
  },
  "SC": {
    "country": "Seychelles",
    "currency": "Seychelles Rupee",
    "currencyCode": "SCR",
    "currencySign": "₨",
    "dialingCode": "+248",
    "countryCode": "SYC",
  },
  "SL": {
    "country": "Sierra Leone",
    "currency": "Sierra Leonean Leone",
    "currencyCode": "SLL",
    "currencySign": "Le",
    "dialingCode": "+232",
    "countryCode": "SLE",
  },
  "SO": {
    "country": "Somalia",
    "currency": "Somali Shilling",
    "currencyCode": "SOS",
    "currencySign": "S",
    "dialingCode": "+252",
    "countryCode": "SOM",
  },
  "ZA": {
    "country": "South Africa",
    "currency": "South African Rand",
    "currencyCode": "ZAR",
    "currencySign": "R",
    "dialingCode": "+27",
    "countryCode": "ZAF",
  },
  "SS": {
    "country": "South Sudan",
    "currency": "South Sudanese pound",
    "currencyCode": "SSP",
    "currencySign": "£",
    "dialingCode": "+211",
    "countryCode": "SSD",
  },
  "SD": {
    "country": "Sudan",
    "currency": "Sudanese pound",
    "currencyCode": "SDG",
    "currencySign": "SD",
    "dialingCode": "+249",
    "countryCode": "SDN",
  },
  "SZ": {
    "country": "Swaziland",
    "currency": "Swazi Lilangeni",
    "currencyCode": "SZL",
    "currencySign": "E",
    "dialingCode": "+268",
    "countryCode": "SWZ",
  },
  "TZ": {
    "country": "Tanzania",
    "currency": "Tanzanian Shilling",
    "currencyCode": "TZS",
    "currencySign": "TSh",
    "dialingCode": "+255",
    "countryCode": "TZA",
  },
  "TG": {
    "country": "Togo",
    "currency": "West African CFA",
    "currencyCode": "XOF",
    "currencySign": "CFA",
    "dialingCode": "+228",
    "countryCode": "TGO",
  },
  "TN": {
    "country": "Tunisia",
    "currency": "Tunisian Dinar",
    "currencyCode": "TND",
    "currencySign": "د.ت",
    "dialingCode": "+216",
    "countryCode": "TUN",
  },
  "UG": {
    "country": "Uganda",
    "currency": "Ugandan Shilling",
    "currencyCode": "UGX",
    "currencySign": "USh",
    "dialingCode": "+256",
    "countryCode": "UGA",
  },
  "ZM": {
    "country": "Zambia",
    "currency": "Zambian Kwacha",
    "currencyCode": "ZMK",
    "currencySign": "ZK",
    "dialingCode": "+260",
    "countryCode": "ZMB",
  },
  "ZW": {
    "country": "Zimbabwe",
    "currency": "Zimbabwean Dollar",
    "currencyCode": "ZWD",
    "currencySign": "\$",
    "dialingCode": "+263",
    "countryCode": "ZWE",
  },
  "AL": {
    "country": "Albania",
    "currency": "Albanian Lek",
    "currencyCode": "ALL",
    "currencySign": "Lek",
    "dialingCode": "+355",
    "countryCode": "ALB",
  },
  "AD": {
    "country": "Andorra",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+376",
    "countryCode": "AND",
  },
  "AT": {
    "country": "Austria",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+43",
    "countryCode": "AUT",
  },
  "BY": {
    "country": "Belarus",
    "currency": "Belarusian Ruble",
    "currencyCode": "BYR",
    "currencySign": "Br",
    "dialingCode": "+375",
    "countryCode": "BLR",
  },
  "BE": {
    "country": "Belgium",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+32",
    "countryCode": "BEL",
  },
  "BA": {
    "country": "Bosnia and Herzegovina ",
    "currency": "Bosnia-Herzegovina Convertible Mark",
    "currencyCode": "BAM",
    "currencySign": "KM",
    "dialingCode": "+387",
    "countryCode": "BIH",
  },
  "BG": {
    "country": "Bulgaria",
    "currency": "Bulgarian Lev",
    "currencyCode": "BGN",
    "currencySign": "лв",
    "dialingCode": "+359",
    "countryCode": "BGR",
  },
  "HR": {
    "country": "Croatia",
    "currency": "Croatian Kuna",
    "currencyCode": "HRK",
    "currencySign": "kn",
    "dialingCode": "+385",
    "countryCode": "HRV",
  },
  "CZ": {
    "country": "Czech Republic",
    "currency": "Czech Koruna",
    "currencyCode": "CZK",
    "currencySign": "Kč",
    "dialingCode": "+420",
    "countryCode": "CZE",
  },
  "DK": {
    "country": "Denmark",
    "currency": "Danish Krone",
    "currencyCode": "DKK",
    "currencySign": "kr.",
    "dialingCode": "+45",
    "countryCode": "DNK",
  },
  "EE": {
    "country": "Estonia",
    "currency": "Estonian Kroon",
    "currencyCode": "EEK",
    "currencySign": "EEK",
    "dialingCode": "+372",
    "countryCode": "EST",
  },
  "FI": {
    "country": "Finland",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+",
    "countryCode": "",
  },
  "FR": {
    "country": "France",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+33",
    "countryCode": "FRA",
  },
  "DE": {
    "country": "Germany",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+49",
    "countryCode": "DEU",
  },
  "GR": {
    "country": "Greece",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+30",
    "countryCode": "GRC",
  },
  "HU": {
    "country": "Hungary",
    "currency": "Hungarian Forint",
    "currencyCode": "HUF",
    "currencySign": "Ft",
    "dialingCode": "+36",
    "countryCode": "HUN",
  },
  "IS": {
    "country": "Iceland",
    "currency": "Icelandic Krona",
    "currencyCode": "ISK",
    "currencySign": "kr",
    "dialingCode": "+354",
    "countryCode": "ISL",
  },
  "IE": {
    "country": "Ireland",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+353",
    "countryCode": "IRL",
  },
  "IT": {
    "country": "Italy",
    "currency": "European Euro ",
    "currencyCode": "EUR ",
    "currencySign": "€ ",
    "dialingCode": "+39",
    "countryCode": "ITA",
  },
  "XK": {
    "country": "Kosovo",
    "currency": "Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+383",
    "countryCode": "XKX",
  },
  "LV": {
    "country": "Latvia",
    "currency": "Latvian Lats",
    "currencyCode": "LVL",
    "currencySign": "Ls",
    "dialingCode": "+371",
    "countryCode": "LVA",
  },
  "LI": {
    "country": "Liechtenstein",
    "currency": "Swiss Franc",
    "currencyCode": "CHF",
    "currencySign": "CHF",
    "dialingCode": "+423",
    "countryCode": "LIE",
  },
  "LT": {
    "country": "Lithuania",
    "currency": "Lithuanian Litas",
    "currencyCode": "LTL",
    "currencySign": "Lt",
    "dialingCode": "+370",
    "countryCode": "LTU",
  },
  "LU": {
    "country": "Luxembourg",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+352",
    "countryCode": "LUX",
  },
  "MK": {
    "country": "Macedonia (FYROM)",
    "currency": "Macedonian Denar",
    "currencyCode": "MKD",
    "currencySign": "ден",
    "dialingCode": "+389",
    "countryCode": "MKD",
  },
  "MT": {
    "country": "Malta",
    "currency": "Maltese Lira",
    "currencyCode": "MTL",
    "currencySign": "₤",
    "dialingCode": "+356",
    "countryCode": "MLT",
  },
  "MD": {
    "country": "Moldova",
    "currency": "Moldovan Leu",
    "currencyCode": "MDL",
    "currencySign": "L",
    "dialingCode": "+373",
    "countryCode": "MDA",
  },
  "MC": {
    "country": "Monaco",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+377",
    "countryCode": "MCO",
  },
  "ME": {
    "country": "Montenegro",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+382",
    "countryCode": "MNE",
  },
  "NL": {
    "country": "Netherlands",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+599",
    "countryCode": "ANT",
  },
  "NO": {
    "country": "Norway",
    "currency": "Norwegian Krone",
    "currencyCode": "NOK",
    "currencySign": "kr",
    "dialingCode": "+47",
    "countryCode": "NOR",
  },
  "PL": {
    "country": "Poland",
    "currency": "Polish Zloty",
    "currencyCode": "PLN",
    "currencySign": "zł",
    "dialingCode": "+48",
    "countryCode": "POL",
  },
  "PT": {
    "country": "Portugal",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+351",
    "countryCode": "PRT",
  },
  "RO": {
    "country": "Romania",
    "currency": "Romanian Leu",
    "currencyCode": "RON",
    "currencySign": "lei",
    "dialingCode": "+40",
    "countryCode": "ROU",
  },
  "SM": {
    "country": "San Marino",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+378",
    "countryCode": "SMR",
  },
  "RS": {
    "country": "Serbia",
    "currency": "Serbian Dinar",
    "currencyCode": "RSD",
    "currencySign": "Дин.",
    "dialingCode": "+381",
    "countryCode": "SRB",
  },
  "SK": {
    "country": "Slovakia",
    "currency": "Slovak Koruna",
    "currencyCode": "SKK",
    "currencySign": "",
    "dialingCode": "+421",
    "countryCode": "SVK",
  },
  "SI": {
    "country": "Slovenia",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+386",
    "countryCode": "SVN",
  },
  "ES": {
    "country": "Spain",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+34",
    "countryCode": "ESP",
  },
  "SE": {
    "country": "Sweden",
    "currency": "Swedish Krona",
    "currencyCode": "SEK",
    "currencySign": "kr",
    "dialingCode": "+46",
    "countryCode": "SWE",
  },
  "CH": {
    "country": "Switzerland",
    "currency": "Swiss Franc",
    "currencyCode": "CHF",
    "currencySign": "CHF",
    "dialingCode": "+41",
    "countryCode": "CHE",
  },

  "Ukraine": {
    "country": "Ukraine",
    "currency": "Ukrainian Hryvnia",
    "currencyCode": "UAH",
    "currencySign": "₴",
    "dialingCode": "+380",
    "countryCode": "UKR",
  },
  "GB": {
    "country": "United Kingdom",
    "currency": "United Kingdom Pound Sterling",
    "currencyCode": "GBP",
    "currencySign": "£",
    "dialingCode": "+44",
    "countryCode": "GBR",
  },
  "VA": {
    "country": "Vatican City (Holy See)",
    "currency": "European Euro",
    "currencyCode": "EUR",
    "currencySign": "€",
    "dialingCode": "+379",
    "countryCode": "VAT",
  },
  "AG": {
    "country": "Antigua and Barbuda",
    "currency": "East Caribbean Dollar",
    "currencyCode": "XCD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "ATG",
  },
  "BS": {
    "country": "Bahamas",
    "currency": "Bahamian Dollar",
    "currencyCode": "BSD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "BHS",
  },
  "BB": {
    "country": "Barbados",
    "currency": "Barbados Dollar",
    "currencyCode": "BBD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "BRB",
  },
  "BZ": {
    "country": "Belize",
    "currency": "Belize Dollar",
    "currencyCode": "BZD",
    "currencySign": "BZ\$",
    "dialingCode": "+501",
    "countryCode": "BLZ",
  },
  "CA": {
    "country": "Canada",
    "currency": "Canadian Dollar",
    "currencyCode": "CAD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "CAN",
  },
  "CR": {
    "country": "Costa Rica",
    "currency": "Costa Rican Colon",
    "currencyCode": "CRC",
    "currencySign": "₡",
    "dialingCode": "+506",
    "countryCode": "CRI",
  },
  "CU": {
    "country": "Cuba",
    "currency": "Cuban Convertible Peso",
    "currencyCode": "CUC",
    "currencySign": "\$",
    "dialingCode": "+53",
    "countryCode": "CUB",
  },
  "DM": {
    "country": "Dominica",
    "currency": "East Caribbean Dollar",
    "currencyCode": "XCD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "DMA",
  },
  "DO": {
    "country": "Dominican Republic",
    "currency": "Dominican Peso",
    "currencyCode": "DOP",
    "currencySign": "RD\$",
    "dialingCode": "+1",
    "countryCode": "DOM",
  },
  "SV": {
    "country": "El Salvador",
    "currency": "United States Dollar",
    "currencyCode": "USD",
    "currencySign": "\$",
    "dialingCode": "+503",
    "countryCode": "SLV",
  },
  "GD": {
    "country": "Grenada",
    "currency": "East Caribbean Dollar",
    "currencyCode": "XCD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "GRD",
  },
  "GT": {
    "country": "Guatemala",
    "currency": "Guatemalan Quetzal",
    "currencyCode": "GTQ",
    "currencySign": "Q",
    "dialingCode": "+502",
    "countryCode": "GTM",
  },
  "HT": {
    "country": "Haiti",
    "currency": "Haitian Gourde",
    "currencyCode": "HTG",
    "currencySign": "G",
    "dialingCode": "+509",
    "countryCode": "HTI",
  },
  "HN": {
    "country": "Honduras",
    "currency": "Honduran Lempira",
    "currencyCode": "HNL",
    "currencySign": "L",
    "dialingCode": "+504",
    "countryCode": "HND",
  },
  "JM": {
    "country": "Jamaica",
    "currency": "Jamaican Dollar",
    "currencyCode": "JMD",
    "currencySign": "J\$",
    "dialingCode": "+1",
    "countryCode": "JAM",
  },
  "MX": {
    "country": "Mexico",
    "currency": "Mexican Peso",
    "currencyCode": "MXN",
    "currencySign": "\$",
    "dialingCode": "+52",
    "countryCode": "MEX",
  },
  "NI": {
    "country": "Nicaragua",
    "currency": "Nicaraguan Córdoba",
    "currencyCode": "NIO",
    "currencySign": "C\$",
    "dialingCode": "+505",
    "countryCode": "NIC",
  },
  "PA": {
    "country": "Panama",
    "currency": "Panamanian Balboa",
    "currencyCode": "PAB",
    "currencySign": "B/.",
    "dialingCode": "+507",
    "countryCode": "PAN",
  },
  "KN": {
    "country": "Saint Kitts and Nevis",
    "currency": "East Caribbean Dollar",
    "currencyCode": "XCD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "KNA",
  },
  "LC": {
    "country": "Saint Lucia",
    "currency": "East Caribbean Dollar",
    "currencyCode": "XCD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "LCA",
  },
  "VC": {
    "country": "Saint Vincent and the Grenadines",
    "currency": "East Caribbean Dollar",
    "currencyCode": "XCD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "VCT",
  },
  "TT": {
    "country": "Trinidad and Tobago",
    "currency": "Trinidad and Tobago Dollar",
    "currencyCode": "TTD",
    "currencySign": "TT\$",
    "dialingCode": "+1",
    "countryCode": "TTO",
  },
  "US": {
    "country": "United States of America",
    "currency": "United States Dollar",
    "currencyCode": "USD",
    "currencySign": "\$",
    "dialingCode": "+1",
    "countryCode": "USA",
  },
  "AR": {
    "country": "Argentina",
    "currency": "Argentine Peso",
    "currencyCode": "ARS",
    "currencySign": "\$",
    "dialingCode": "+54",
    "countryCode": "ARG",
  },
  "BO": {
    "country": "Bolivia",
    "currency": "Bolivian Boliviano",
    "currencyCode": "BOB",
    "currencySign": "\$b",
    "dialingCode": "+591",
    "countryCode": "BOL",
  },
  "BR": {
    "country": "Brazil",
    "currency": "Brazilian Real",
    "currencyCode": "BRL",
    "currencySign": "R\$",
    "dialingCode": "+55",
    "countryCode": "BRA",
  },
  "CL": {
    "country": "Chile",
    "currency": "Chilean Peso",
    "currencyCode": "CLP",
    "currencySign": "\$",
    "dialingCode": "+56",
    "countryCode": "CHL",
  },
  "CO": {
    "country": "Colombia",
    "currency": "Colombian Peso",
    "currencyCode": "COP",
    "currencySign": "\$",
    "dialingCode": "+57",
    "countryCode": "COL",
  },
  "EC": {
    "country": "Ecuador",
    "currency": "United States Dollar",
    "currencyCode": "USD",
    "currencySign": "\$",
    "dialingCode": "+593",
    "countryCode": "ECU",
  },
  "GY": {
    "country": "Guyana",
    "currency": "Guyanese Dollar",
    "currencyCode": "GYD",
    "currencySign": "\$",
    "dialingCode": "+592",
    "countryCode": "GUY",
  },
  "PY": {
    "country": "Paragua",
    "currency": "Paraguay Guarani",
    "currencyCode": "PYG",
    "currencySign": "Gs",
    "dialingCode": "+595",
    "countryCode": "PRY",
  },
  "PE": {
    "country": "Per",
    "currency": "Peruvian Nuevo Sol",
    "currencyCode": "PEN",
    "currencySign": "S/.",
    "dialingCode": "+51",
    "countryCode": "PER",
  },
  "SR": {
    "country": "Suriname",
    "currency": "Suriname Dollar",
    "currencyCode": "SRD",
    "currencySign": "\$",
    "dialingCode": "+597",
    "countryCode": "SUR",
  },
  "UY": {
    "country": "Uruguay",
    "currency": "Uruguayan peso",
    "currencyCode": "UYU",
    "currencySign": "\$U",
    "dialingCode": "+598",
    "countryCode": "URY",
  },
  "VE": {
    "country": "Venezuela",
    "currency": "Venezuelan Bolivar",
    "currencyCode": "VEF",
    "currencySign": "Bs",
    "dialingCode": "+58",
    "countryCode": "VEN",
  },
  "FJ": {
    "country": "Fiji",
    "currency": "Fiji Dollar",
    "currencyCode": "FJD",
    "currencySign": "\$",
    "dialingCode": "+679",
    "countryCode": "FJI",
  },
  "KI": {
    "country": "Kiribati",
    "currency": "Australian Dollar",
    "currencyCode": "AUD",
    "currencySign": "\$",
    "dialingCode": "+686",
    "countryCode": "KIR",
  },
  "MH": {
    "country": "Marshall Island",
    "currency": "United States Dollar",
    "currencyCode": "USD",
    "currencySign": "\$",
    "dialingCode": "+692",
    "countryCode": "MHL",
  },
  "FM": {
    "country": "Micronesia",
    "currency": "United States Dollar",
    "currencyCode": "USD",
    "currencySign": "\$",
    "dialingCode": "+691",
    "countryCode": "FSM",
  },
  "NR": {
    "country": "Nauru",
    "currency": "Australian Dollar",
    "currencyCode": "AUD",
    "currencySign": "\$",
    "dialingCode": "+674",
    "countryCode": "NRU",
  },
  "NZ": {
    "country": "New Zealand",
    "currency": "New Zealand Dollar",
    "currencyCode": "NZD",
    "currencySign": "\$",
    "dialingCode": "+64",
    "countryCode": "NZL",
  },
  "PW": {
    "country": "Palau",
    "currency": "United States Dollar",
    "currencyCode": "USD",
    "currencySign": "\$",
    "dialingCode": "+680",
    "countryCode": "PLW",
  },
  "PG": {
    "country": "Papua New Guinea",
    "currency": "New Guinea Kina",
    "currencyCode": "PGK",
    "currencySign": "K",
    "dialingCode": "+675",
    "countryCode": "PNG",
  },
  "WS": {
    "country": "Samoa",
    "currency": "Samoan Tala",
    "currencyCode": "WST",
    "currencySign": "WS\$",
    "dialingCode": "+685",
    "countryCode": "WSM",
  },
  "SB": {
    "country": "Solomon Islands",
    "currency": "Solomon Islands Dollar",
    "currencyCode": "SBD",
    "currencySign": "\$",
    "dialingCode": "+677",
    "countryCode": "SLB",
  },
  "TO": {
    "country": "Tonga",
    "currency": "Tongan Pa'Anga",
    "currencyCode": "TOP",
    "currencySign": "T\$",
    "dialingCode": "+676",
    "countryCode": "TON",
  },
  "TV": {
    "country": "Tuvalu",
    "currency": "Australian Dollar",
    "currencyCode": "AUD",
    "currencySign": "\$",
    "dialingCode": "+688",
    "countryCode": "TUV",
  },
};
