// ignore_for_file: constant_identifier_names

enum FirebaseMessageOrigin { INITIAL_MESSAGE, ON_MESSAGE_OPENED_APP, ON_MESSAGE, ON_BACKGROUND_MESSAGE, ON_CLICKED_MESSAGE }

enum ShowRideShareNav { DESTINATION_SELECTION, PICKUP_SELECTION, PAYMENT_METHOD_SELECTION, DRIVER_FOUND, DRIVER_RIDER, DRIVER_TRIP, TRIP }

enum RiderTileNav { SEARCH_DESTINATION_TILE, REQUEST_A_RIDE_TILE, SHOW_PLEASE_WAIT_TILE, SHOW_DRIVER_FOUND }

enum ShowNave { MOOWE_CHAT, MOOWE_PAY, MOOWE_RIDE_SHARE, MOOWE_MARKET }

enum OpenContactsScreenOrigin { FROM_CHAT_PAGE, FROM_MOOWE_PAY, FROM_GROUP_CHAT, FROM_PROJECT_CHAT }

enum UserActionType {
  CREATE_NEW_GROUP_OR_PROJECT_CHAT,
  USER_ACTION_NOT_SET,
  CREATE_NEW_CHAT,
  SEND_CASH_DIRECT_FROM_MOOWE_PAY,
  CREATE_CONTRACT,
  SEND_CASH_IN_PRIVATE_CHAT,
  SEND_CASH_IN_GROUP_CHAT,
  SEND_CASH_PROJECT_CHAT,
  SEND_CASH_TO_MOMO,
  SEND_CASH_TO_BANK_ACCOUNT,
  CASH_OUT_TO_BANK_ACCOUNT,
  ADD_NEW_MEMBER_TO_GROUP_OR_PROJECT,
  PAY_INTO_CONTRACT,
  PROCESS_CONTRACT,
  BILL_PAY,
  REQUEST_PAYMENT,
  TRANSFER_CASH_TO_BANK,
  ADD_MEMBER_TO_BUSINESS_ACCOUNT
}

enum TransactionActionType {
  TRANSFER_FUNDS_FROM_GROUP_CHAT_TO_A_PEER,
  PAY_BILL_FROM_GROUP_CHAT,
  SCAN_FROM_GROUP_CHAT,
  SEND_CASH_DIRECT_FROM_MOOWE_PAY,
  SEND_CASH_IN_PRIVATE_CHAT,
  SEND_CASH_IN_GROUP_CHAT,
  CASH_IN_FROM_BANK,
  SEND_CASH_PROJECT_CHAT,
  SEND_CASH_TO_MOMO,
  SEND_CASH_TO_BANK_ACCOUNT,
  CASH_OUT_TO_BANK_ACCOUNT,
  PAY_INTO_CONTRACT,
  PROCESS_CONTRACT,
  SEND_CONVERTED_CURRENCY,
  SEND_CASH_WITH_PROJECT_SCAN_CAMERA,
  OFFLINE_TRANSACTION,
  SCAN_QR_CODE_FROM_MOOWE_PAY,
  PROCESS_CHAT_GROUP_FUNDING,
  BILL_PAY,
  REQUEST_PAYMENT,
  TRANSFER_CASH_TO_BANK,
  EXCHANGE_IN_PRIVATE_CHAT,
  EXCHANGE_IN_GROUP_CHAT_OR_PROJECT_CHAT,
  EXCHANGE_GROUP_FUNDING,
  EXCHANGE_FROM_MOOWE_PAY,
  PROCESS_REQUEST_PAYMENT,
  DECLINE_PAYMENT_REQUEST,
  FUND_A_MEMBER,
  MOOWE_RIDE_CHARGE,
  CHECK_OUT_PAYMENT,
  RELEASE_CONTRACT_PAYMENT,
  STORE_SCANNED_PAYMENT
}

enum ChatTypes { BUSINESS_CHAT, STORE_CHAT, PRIVATE_CHAT, GROUP_CHAT, PROJECT_CHAT, FUND_RAISE, SUSU }

enum CallHistoryActions { MISSED_CALL, ANSWERED_CALL, RECORD_CALL }

enum NotificationDataType { CALL_DATA, CHAT_DATA, MONEY_DATA, STORE_PAYMENT, DRIVER_AT_LOCATION_DATA, REQUEST_ACCEPTED_DATA, RIDE_REQUEST_DATA, REQUEST_PAYMENT, BUSINESS_ADMIN_ADD_MEMBER }

enum ChatMessageType {
  MONEY,
  MESSAGE,
  IMAGE,
  MULTIPLE_IMAGES,
  VIDEO_FILE,
  AUDIO_FILE,
  VOICE_FILE,
  ASK_FOR_PERMISSION_TO_CASH_OUT,
  SURVEY_QUESTION,
  APPROVE_DISAPPROVE,
  APPROVE,
  DISAPPROVE,
  GROUP_CALL,
  FUNDING,
  FUNDING_COMPLETE,
  CALL_ANSWERED,
  REQUESTING,
  CONTRACT
}

enum ChatServicesActions {
  SAVE_DEVICE_TOKEN,
  SEND_MESSAGE,
  UPDATE_IS_READ_MESSAGE,
  CREATE_NEW_GROUP_OR_PROJECT_CHAT,
  CREATE_NEW_PRIVATE_CHAT,
  APPROVE_BENEFICIARY,
  DISAPPROVE_BENEFICIARY,
  ADD_MEMBER_TO_PROJECT_OR_GROUP,
  MAKE_MEMBER_PROJECT_MANAGER,
  REVOKE_MANAGER_RIGHTS,
  LOCAL_FIREBASE_LISTENERS,
  ADD_MEMBER_TO_BUSINESS_ACCOUNT,
  UPDATE_MEMBER_STATUS_ON_LINE,
  UPDATE_MEMBER_STATUS_OFF_LINE,
}

enum JitsiCallActions { GROUP_CALL, PRIVATE_CALL, JOINT_GROUP_CALL_BUTTON, INCOMING_CALL }

enum CallActionStatus {
  ON_CALL,
  CALL_START,
  OFFER_SDP,
  OFFER_SDP_RECEIVED,
  ANSWER_SDP,
  ANSWER_SDP_RECEIVED,
  CALLER_CANDIDATE,
  CALLER_CANDIDATE_RECEIVED,
  RECEIVER_CANDIDATE,
  RECEIVER_CANDIDATE_RECEIVED,
  ANSWER_CALL,
  SET_CANDIDATE,
  END_CALL,
  CALLER_HANG_UP,
  CALLER_HANG_UP_AFTER_NO_ANSWER,
  CALLER_HANG_ENDED_CALL,
  RECEIVER_HANG_UP,
  RECEIVER_ENDED_CALL,
  RECEIVER_REJECT
}

enum CallType { VIDEO_CALL, VOICE_CALL }

enum TransactionType { REQUEST_PAYMENT, DECLINE_PAYMENT_REQUEST, REQUEST_PAID, BILL_PAY, CASH_OUT, EXPENSE, INCOME, CONTRIBUTION, FUNDING }

enum TransactionPayloadType {
  REQUEST_PAYMENT,
  REQUEST_PAID,
  TRANSACTION,
  EXCHANGE_TRANSACTION,
  DECLINE_PAYMENT_REQUEST,
}

enum BusinessServiceAction { CREATE_NEW_BUSINESS_ACCOUNT, CREATE_BUSINESS_CHAT_ROOM, PAY_A_BILL }

enum MediaTypeAction {
  IMAGE,
  MULTIPLE_IMAGES,
  TAKE_A_PHOTO,
  PICK_VIDEO_FROM_GALLERY,
  TAKE_VIDEO,
}

enum ChatScreenSendActionType { SEND_MEDIA, SEND_TEXT_MESSAGE }

enum SubscribedServices { ACCEPT_PAYMENTS_BUSINESS_ACCOUNT, MOOWE_RIDER, MOOWE_DRIVER, MOOWE_POINT_OF_SALE }

enum CurrentScreen {
  MOOWE_CHAT_SCREEN,
  MOOWE_PAY_SCREEN,
  MOOWE_RIDER_SCREEN,
  MOOWE_DRIVER_SCREEN,
  MOOWE_MARKET_SCREEN,
  MOOWE_GROUP_CHAT_SCREEN,
  MOOWE_PROJECT_CHAT_SCREEN,
  MOOWE_PRIVATE_CHAT_SCREEN,
  MOOWE_CALL_SCREEN
}

enum DriverCurrentScreen { MOOWE_DRIVER_HAS_NEW_RIDE, MOOWE_DRIVER_HOME_SCREEN }

enum RideRequestStatus {
  ACCEPTED,
  CANCELLED,
  TIMEOUT,
  SEARCHING,
  NEW_SIGNUP,
  REQUESTING_A_RIDE,
  ARRIVED,
  START_TRIP,
  END_TRIP,
  ON_TRIP,
  TRIP_ENDED,
  DRIVER_FOUND,
}

enum RideType { LUX, E_CON, BIKE }

enum CurrencyTypes {
  USD,
  GHS,
  NGN,
  GBP,
}

enum CallResponds { CALLER_ANSWER, RECEIVER_ANSWER, CALLER_HANGED_UP, RECEIVER_HANGED_UP, PHONE_RINGING, INCOMING_CALL, RECEIVER_DECLINED, MISSED_CALL }

enum IncomingCallOrOutGoingCall { INCOMING_CALL, OUTGOING_CALL }

enum AuthScreens { LOGIN_SCREEN, HOME_SCREEN, REGISTER_SCREEN }

enum UserBusinessType { MERCHANT_STORE, ACCEPT_PAYMENT_SERVICE }

enum ExtraDataType { GENERAL, ProductSize, ProductColor }

enum ShoppingCartOrigin { SHOPPING, HISTORY }

enum MarketAppBarActions { SEARCH, CANCEL_SEARCH }
enum ContactAppBarActions { SEARCH, CANCEL_SEARCH }

enum CashOutType { BUSINESS_DAY, INSTANT }

enum NotificationOriginating { onMessage, onMessageOpenedApp, background }

enum GroupMemberDisplayType { DISPLAY_TYPE_NOT_SET, TRANSFER_PAYMENT_FROM_GROUP_CARD, DISPLAY_MEMBERS_OF_GROUP }

enum FundingActionType { PEER_TO_PEER_TRANSFER, TRANSFER_FUNDS_FROM_GROUP_TO_A_PEER, TRANSFER_FUNDS_FROM_GROUP_TO_A_BUSINESS, TRANSFER_FUNDS_FROM_WALLET_TO_A_BUSINESS, TRANSFER_FUNDS_INTO_GROUP }

enum CameraScanLocation { CAMERA_FROM_GROUP_CHAT, CAMERA_FROM_WALLET }

enum PayBillActionLocation { BILL_LOCATION_NOT_SET, PAY_A_BILL_FROM_GROUP, PAY_A_BILL_FROM_WALLET }

enum StoreShowQRCodOrChat { SHOW_STORE_CHAT, SHOW_STORE_QRCODE }

enum SameCurrencyType { SAME_CURRENCY, CURRENCY_EXCHANGE }
enum CashOutFrom { CASH_OUT_NOT_SET, BUSINESS_CASH_OUT, WALLET_CASH_OUT}

class EnumServices {
  FirebaseMessageOrigin? firebaseMessageOrigin;
  NotificationDataType? notificationDataType;
  ShowNave? showNave = ShowNave.MOOWE_CHAT;
  ShowRideShareNav? showRideShareNav = ShowRideShareNav.DESTINATION_SELECTION;
  OpenContactsScreenOrigin? openContactsScreenOrigin;
  UserActionType userActionType = UserActionType.USER_ACTION_NOT_SET;
  ChatTypes? chatTypes;
  CallType? callType;
  TransactionActionType? transactionActionType;
  ChatServicesActions? chatServicesActions;
  ChatMessageType? chatMessageType;
  TransactionType? transactionType;
  BusinessServiceAction? businessServiceAction;
  MediaTypeAction? mediaTypeAction;
  ChatScreenSendActionType chatScreenSendActionType = ChatScreenSendActionType.SEND_TEXT_MESSAGE;
  RiderTileNav riderTileNav = RiderTileNav.SEARCH_DESTINATION_TILE;
  SubscribedServices rideSharScreen = SubscribedServices.MOOWE_RIDER;
  CurrentScreen currentScreen = CurrentScreen.MOOWE_CHAT_SCREEN;
  AuthScreens authScreens = AuthScreens.LOGIN_SCREEN;
  UserBusinessType userBusinessType = UserBusinessType.ACCEPT_PAYMENT_SERVICE;
  DriverCurrentScreen driverCurrentScreen = DriverCurrentScreen.MOOWE_DRIVER_HOME_SCREEN;
  CurrencyTypes currencyTypes = CurrencyTypes.USD;
  ShoppingCartOrigin shoppingCartOrigin = ShoppingCartOrigin.SHOPPING;
  CashOutType cashOutType = CashOutType.INSTANT;
  FundingActionType fundingActionType = FundingActionType.PEER_TO_PEER_TRANSFER;
  CameraScanLocation cameraScanLocation = CameraScanLocation.CAMERA_FROM_WALLET;
  PayBillActionLocation payBillActionLocation = PayBillActionLocation.BILL_LOCATION_NOT_SET;
  SameCurrencyType sameCurrencyType = SameCurrencyType.SAME_CURRENCY;
  CashOutFrom cashOutFrom = CashOutFrom.CASH_OUT_NOT_SET;
  ContactAppBarActions appBarActions = ContactAppBarActions.CANCEL_SEARCH;
}
