// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi4RqSG5MCESXfeCtsrDuj1RW4079wO1o',
    appId: '1:295186155824:web:945b663505fd70603660f5',
    messagingSenderId: '295186155824',
    projectId: 'mooweapp',
    authDomain: 'mooweapp.firebaseapp.com',
    databaseURL: 'https://mooweapp-default-rtdb.firebaseio.com',
    storageBucket: 'mooweapp.appspot.com',
    measurementId: 'G-16KYWMD2Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEVEevHU-FiExSh7j6Z6I6HEGVdDJFAbc',
    appId: '1:295186155824:android:d58b58c5c62718193660f5',
    messagingSenderId: '295186155824',
    projectId: 'mooweapp',
    databaseURL: 'https://mooweapp-default-rtdb.firebaseio.com',
    storageBucket: 'mooweapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChRxfVwY4FfIh54UevryYRdk1UfwfSq-0',
    appId: '1:295186155824:ios:5c43e33ecdb91dac3660f5',
    messagingSenderId: '295186155824',
    projectId: 'mooweapp',
    databaseURL: 'https://mooweapp-default-rtdb.firebaseio.com',
    storageBucket: 'mooweapp.appspot.com',
    androidClientId: '295186155824-7jjuf6m2ruibr2tc57rlntbbodnb55ms.apps.googleusercontent.com',
    iosClientId: '295186155824-6rdq012uu6i3fpc6dfv0kdk3ubqm6kgb.apps.googleusercontent.com',
    iosBundleId: 'com.app.mowe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChRxfVwY4FfIh54UevryYRdk1UfwfSq-0',
    appId: '1:295186155824:ios:04580c96866a0ad53660f5',
    messagingSenderId: '295186155824',
    projectId: 'mooweapp',
    databaseURL: 'https://mooweapp-default-rtdb.firebaseio.com',
    storageBucket: 'mooweapp.appspot.com',
    androidClientId: '295186155824-7jjuf6m2ruibr2tc57rlntbbodnb55ms.apps.googleusercontent.com',
    iosClientId: '295186155824-n8i9of1v42a7hncumj6vsbgkk1srr23m.apps.googleusercontent.com',
    iosBundleId: 'com.mooweapp.mooweapp',
  );
}
