# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  desc "This is to export app to app store"
  lane :export_app do
  gym(
  project: "Runner.xcodeproj",
  scheme: "Runner",
  clean: true,
  export_xcargs: "-allowProvisioningUpdates",
  output_name: "ReleaseApp.ipa"
  )
  end


  lane :release do
    sync_code_signing
    disable_automatic_code_signing(path: "Runner.xcodeproj")
    build_app
    enable_automatic_code_signing(path: "Runner.xcodeproj")
    upload_to_testflight
  end


end
