# This is a basic workflow to help you get started with Actions
name: CD / CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*" # on every version tag will build a new android artifact example: v3.1.2+6
jobs:
  test:
    name: Mowe CI / CD
    runs-on: ubuntu-latest

    steps:

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'your_signing_keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}



      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
#      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
#      - uses: r0adkll/sign-android-release@v1
#      - name: Sign app APK
#          # ID used to access action output
#        id: sign_app
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: # optional, default is artifact
          path: build/app/outputs/bundle/release/app-release.apk


#      - run: |
#         flutter build ios --no-codesign
#         cd build/ios/iphoneos
#         mkdir Payload
#         cd Payload
#         ln -s ../Runner.app
#         cd ..
#         zip -r app.ipa Payload
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#         artifacts: "build/ios/iphoneos/app.ipa"
#         tag: v1.0.${{ github.run_number }}
#         token: ${{ secrets.TOKEN }}


